name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t mkoppal/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true mkoppal/react-test npm test

      - run: docker build -t mkoppal/multi-client ./client
      - run: docker build -t mkoppal/multi-nginx ./nginx
      - run: docker build -t mkoppal/multi-server ./server
      - run: docker build -t mkoppal/multi-worker ./worker

      - run: docker push mkoppal/multi-client
      - run: docker push mkoppal/multi-nginx
      - run: docker push mkoppal/multi-server
      - run: docker push mkoppal/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-378134920004
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
